### ISSUE TITLE
Time Machine

### ISSUE THREAD

**Issue by Incrested** [Incrested/Miku-Chan#30]
Revert the Version of Miku on a server based on the commit on GitHub.

Command: $version
Usage: Reverts Miku's Version and Tells Version

Possible Args:
- "current" ~ Update to Latest
- "[commit SHA]" ~ Update to Commit Mentioned
- "v[version #]# ~ Update to Version Release
- "beta" ~ Move to Beta Tree of GitHub
- "stable" ~ Move to Stable Tree of GitHub

Examples:
$version current
$version edf9e9
$version v0
$version beta
$version stable

**Comment by Incrested** [comment]
Added in 67c3515. Could be bugged.

**Comment by Incrested** [comment]
Unfunctional.

**Comment by Incrested** [comment]
Semi-Impossible. Leaving "$version v1" to give access to hosting v1 personally.

**Comment by ultraMLGcode** [comment]
Locked because we won't be adding this feature due to hosting costs.
