### ISSUE TITLE
Entire Bot Doesn't Work

### ISSUE THREAD

**Issue by Incrested** [Incrested/Miku-Chan#4]
The bot probably has a really obvious (and dumb) reason of not working at all. Heroku announces the error but can still log in, but then "cut and runs" right after.

**Comment by d-nni3l** [comment]
omg nvm lol

**Comment by d-nni3l** [comment]
The issue is **partly** fixed.

Reference #9 for more info.

**Comment by Incrested** [comment]
#8 has been partially repaired. #9 is on my to-do list.

**Comment by Incrested** [comment]
As of edit on #9, the bot commands work. Just need to fix the status.

**Comment by Incrested** [comment]
As of https://github.com/Incrested/Miku-Chan/commit/c2d1fd3a3b44b12aea24e102e11c1424061a7951, Miku-Chan has been fixed.
