### ISSUE TITLE
Backup Plans with the Loss of Net Neutrality

### ISSUE THREAD

**Issue by Incrested** [Incrested/Miku-Chan#40]
Net Neutrality just got removed. Does anyone have ideas for other places to host the bot? I've assumed places like AWS or Azure, but they might be a bit out of the budget.

To read more on net neutrality, The Verge wrote [this](https://www.theverge.com/2017/12/14/16776154/fcc-net-neutrality-vote-results-rules-repealed) to tell us about the vote around 20 minutes ago.

I also believe I can convince the British hosting we've got to host up Miku-Chan for a month or two, but after that, she'll want us to not suck up her Net Neutralized internet.

Just reply with possible hosting providers. Cheers!

**Comment by ultraMLGcode** [comment]
They probably won’t block Heroku, but AWS is the best plan if we need to switch.

**Comment by ultraMLGcode** [comment]
AWS EC2 is what we would use. It’s free for a year.

**Comment by Incrested** [comment]
Alrighty. If Net Neutralities disappearence screws over Heroku, then I say we start up AWS. One year and then what price point, @ultraMLGcode ?

**Comment by Incrested** [comment]
Backup plan is AWS EC2, only if Heroku is throttled by more than 5 megabytes per second. Start your ping testing, folks!
