### ISSUE TITLE
Version 1 Not Finished

### ISSUE THREAD

**Issue by Incrested** [Incrested/Miku-Chan#41]
Not to point fingers, but I already finished my load. @ultraMLGcode is basically the only one who needs to help finish up on the v1 branch. Then, we can get to work on v2, which will be due Jan. 1st, 2019. For issues, check [here](https://github.com/Incrested/Miku-Chan/milestone/2)

**Comment by ultraMLGcode** [comment]
Version 1 has been finished! Sorry for the (extreme) delay.
